[tool.poetry]
name = "portfolio-diagram"
version = "0.1.0"
description = ""
authors = ["amauryval <amauryval@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.11.0"
diagrams = "^0.23.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
